# -*- coding: utf-8 -*-
"""Copy of LinkedIn Vs Eventbrite.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1txRMZ6MbKyz4AFH-20OKdeU8lxI8HncK
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#mounting the csv files into the colab

from google.colab import files
uploaded=files.upload()

import glob

# list all csv files only
csv_files = glob.glob('*.{}'.format('csv'))
csv_files

import pandas as pd

df_csv_append = pd.DataFrame()

# append the CSV files
for file in csv_files:
    df = pd.read_csv(file)
    df_csv_append = df_csv_append.append(df, ignore_index=True)

df_csv_append

df_csv_append.fillna(0)

# save the data to a report csv file
df_csv_append.to_csv("report.csv", index= False)

# Find duplicate data based on rows

#import modules
import pandas as pd
#reading the csv file
report_data = pd.read_csv('report.csv')
report_data.head()
report_data.columns
duplicateRowsDF = report_data[report_data.duplicated()]
print("Duplicate Rows except first occurrence based on all columns are :")
print(duplicateRowsDF)

#list the files in the directory
! ls

# Display the conent of the report file(the output file)
! cat report.csv

# importing the pandas library
import pandas as pd

# reading the csv file using read_csv
# storing the data frame in variable called df
df = pd.read_csv('report.csv')

# creating a list of column names by
# calling the .columns
list_of_column_names = list(df.columns)

# displaying the list of column names
print('List of column names : ',
      list_of_column_names)

import pandas as pd

df=pd.read_csv('report.csv')


#FINDING MAX AND MIN
p=df['Order Date'].max()
q=df['Order Date'].min()


print(q)
print(p)

# Lets select few columns for this exercise
columns_to_select = ['Order #', 'Order Date', 'Quantity', 'Total Paid', 'Attendee Status', 'Price Tier', 'Currency']

columns_to_select

SELECT ('First Name')
FROM 'report.csv';